[package]
name = "speexdsp"
version = "0.1.1"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
description = "Bindings for the speexdsp library"
homepage = "https://github.com/rust-av/speexdsp-rs"
repository = "https://github.com/rust-av/speexdsp-rs"
keywords = ["audio", "resampler"]
categories = ["api-bindings"]
license = "MIT"
readme = "README.md"

[features]
build = ["speexdsp-sys/build"]

[dependencies]
speexdsp-sys = { version = "0.1.1", path = "speexdsp-sys" }

[dev-dependencies]
proptest = "0.7.0"

[workspace]
members = ["speexdsp-sys"]
